/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Lab1;

public class Library {
	public static void main(String arg[]) {
		Library lib = new Library();
		if(lib.someLibraryMethod())
			System.out.println("Hello, world");
	}

	public boolean someLibraryMethod() {
		// TODO Auto-generated method stub
		return false;
	}
	
}

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
https://github.com/xillioxi/Lab1.git